### ISSUE TITLE
Replace `random` with `secrets` module to improve generated passwords

### ISSUE THREAD

**Issue by boidolr** [federicocalendino/alfred-pwd-gen#6]
According to the description of [`secrets`](https://docs.python.org/3/library/secrets.html):
> The [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) module is used for generating cryptographically strong random numbers suitable for managing data such as passwords, account authentication, security tokens, and related secrets.
> In particular, [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) should be used in preference to the default pseudo-random number generator in the [random](https://docs.python.org/3/library/random.html#module-random) module, which is designed for modelling and simulation, not security or cryptography.

I think `secrets` should be a drop-in replacement for `random` in this workflow, and is available from Python 3.6 onwards.

**Comment by fedecalendino** [comment]
I just released v1.9.0 with the suggested change.

Thanks!
Fede
